//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppLogic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppLogic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;name&quot;:&quot;Goroka&quot;,&quot;city&quot;:&quot;Goroka&quot;,&quot;country&quot;:&quot;Papua New Guinea&quot;,&quot;IATA&quot;: &quot;GKA&quot;, &quot;ICAO&quot;: &quot;AYGA&quot;, &quot;lat&quot;: &quot;-6.081689834590001&quot;, &quot;lon&quot;:&quot;145.391998291&quot;,&quot;timezone&quot;: &quot;10&quot;},{&quot;name&quot;: &quot;Madang &quot;, &quot;city&quot;: &quot;Madang&quot;,&quot;country&quot;: &quot;Papua New Guinea&quot;, &quot;IATA&quot;: &quot;MAG&quot;, &quot;ICAO&quot;: &quot;AYMD&quot;, &quot;lat&quot;: &quot;-5.20707988739&quot;, &quot;lon&quot;: &quot;145.789001465&quot;, &quot;timezone&quot;: &quot;10&quot;},{&quot;name&quot;: &quot;Mount Hagen Kagamuga &quot;, &quot;city&quot;: &quot;Mount Hagen&quot;, &quot;country&quot;: &quot;Papua New Guinea&quot;, &quot;IATA&quot;: &quot;HGU&quot;, &quot;ICAO&quot;: &quot;AYMH&quot;, &quot;lat&quot;: &quot;-5.826789855957031&quot;, &quot;lon&quot;: &quot;144.29600524902344&quot;, &quot;timez [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Airports {
            get {
                return ResourceManager.GetString("Airports", resourceCulture);
            }
        }
    }
}
